# -*- coding: utf-8 -*-
"""AIR_Quality_INDIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144iLXLOcb0UOktVWQBxJ_7qyQgpoamFC
"""

import pandas as pd
import matplotlib.pyplot as pl
df = pd.read_csv("/content/Air Quality in INDIA.csv")
from matplotlib.backends.backend_pdf import PdfPages

so2_cols = [col for col in df.columns if "SO2" in col]
markers = ['o', 's', '^', 'D', '*', 'v', 'P', 'X']
plt.figure(figsize=(15,7))

for idx, col in enumerate(so2_cols):
    year = col.split(" ")[0]
    cities = df["Cities"]
    so2_values = df[col]

    plt.plot(
        cities,
        so2_values,
        marker=markers[idx % len(markers)],
        linewidth=2,
        label=f"{year}"
    )

plt.title("SO₂ Pollution Levels Across Cities (Combined Years)", fontsize=16)
plt.xlabel("Cities")
plt.ylabel("SO₂ (µg/m³)")
plt.xticks(rotation=90)
plt.grid(True)
plt.legend(title="Years", fontsize=12)

plt.tight_layout()
plt.show()

no2_cols = [col for col in df.columns if "NO2" in col]

markers = ['o', 's', '^', 'D', '*', 'v', 'P', 'X']
plt.figure(figsize=(15,7))

for idx, col in enumerate(no2_cols):
    year = col.split(" ")[0]
    cities = df["Cities"]
    no2_values = df[col]

    plt.plot(
        cities,
        no2_values,
        marker=markers[idx % len(markers)],
        linewidth=2,
        label=f"{year}"
    )

plt.title("NO₂ Pollution Levels Across Cities (Combined Years)", fontsize=16)
plt.xlabel("Cities")
plt.ylabel("NO₂ (µg/m³)")
plt.xticks(rotation=90)
plt.grid(True)
plt.legend(title="Years", fontsize=12)

plt.tight_layout()
plt.show()

pm10_cols = [col for col in df.columns if "PM10" in col]
markers = ['o', 's', '^', 'D', '*', 'v', 'P', 'X']

plt.figure(figsize=(15,7))

for idx, col in enumerate(pm10_cols):
    year = col.split(" ")[0]
    cities = df["Cities"]
    pm10_values = df[col]

    plt.plot(
        cities,
        pm10_values,
        marker=markers[idx % len(markers)],
        linewidth=2,
        label=f"{year}"
    )

plt.title("PM10 Pollution Levels Across Cities (Combined Years)", fontsize=16)
plt.xlabel("Cities")
plt.ylabel("PM10 (µg/m³)")
plt.xticks(rotation=90)
plt.grid(True)
plt.legend(title="Years", fontsize=12)

plt.tight_layout()
plt.show()

pollutant_cols = [col for col in df.columns if any(x in col for x in ["SO2", "NO2", "PM10"])]

heatmap_df = df[pollutant_cols]
heatmap_df.index = df["Cities"]
plt.figure(figsize=(26, 12))

sns.heatmap(
    heatmap_df,
    cmap="coolwarm",
    linewidths=0.5,
    linecolor="white",
    annot=False,
    cbar_kws={'label': 'Pollution Level (µg/m³)'}
)

plt.title("Pollution Heatmap Across Indian Cities (SO₂, NO₂, PM₁₀, All Years)",
          fontsize=22, weight='bold', pad=20)

plt.xticks(rotation=45, ha="right", fontsize=12)
plt.yticks(fontsize=12)

plt.tight_layout()
plt.show()

pollutants = ["SO2", "NO2", "PM10"]

results = []

for pollutant in pollutants:
    cols = [col for col in df.columns if pollutant in col]

    for col in cols:
        year = col.split(" ")[0]

        # Highest
        max_value = df[col].max()
        max_city = df.loc[df[col] == max_value, "Cities"].values[0]

        # Lowest
        min_value = df[col].min()
        min_city = df.loc[df[col] == min_value, "Cities"].values[0]

        results.append([year, pollutant, max_city, max_value, min_city, min_value])

summary_df = pd.DataFrame(results,
                          columns=["Year", "Pollutant", "Highest City", "Highest Value",
                                   "Lowest City", "Lowest Value"])

summary_df

pollutants = ["SO2", "NO2", "PM10"]

for pollutant in pollutants:

    # Extract columns like "2015 - SO2"
    cols = [col for col in df.columns if pollutant in col]

    years = []
    highest_cities = []
    highest_values = []
    lowest_cities = []
    lowest_values = []

    # Find highest & lowest per year
    for col in cols:
        year = col.split(" ")[0]

        # Highest
        max_value = df[col].max()
        max_city = df.loc[df[col] == max_value, "Cities"].values[0]

        # Lowest
        min_value = df[col].min()
        min_city = df.loc[df[col] == min_value, "Cities"].values[0]

        years.append(year)
        highest_cities.append(max_city)
        highest_values.append(max_value)

        lowest_cities.append(min_city)
        lowest_values.append(min_value)
    plt.figure(figsize=(5,3.8))
    plt.bar(years, highest_values)

    for i, city in enumerate(highest_cities):
        plt.text(years[i], highest_values[i], city, ha='center', va='bottom', fontsize=9)

    plt.title(f"Highest {pollutant} Levels – City with Maximum Pollution Each Year")
    plt.ylabel(f"{pollutant} Value")
    plt.xlabel("Year")
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(5,3.8))
    plt.bar(years, lowest_values, color='green')

    for i, city in enumerate(lowest_cities):
        plt.text(years[i], lowest_values[i], city, ha='center', va='bottom', fontsize=9)

    plt.title(f"Lowest {pollutant} Levels – City with Minimum Pollution Each Year")
    plt.ylabel(f"{pollutant} Value")
    plt.xlabel("Year")
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

# Extract years (2015, 2016, 2017)
years = ["2015", "2016", "2017"]

total_pollution = []

for year in years:
    so2 = df[f"{year} - SO2"].sum()
    no2 = df[f"{year} - NO2"].sum()
    pm10 = df[f"{year} - PM10"].sum()

    total = so2 + no2 + pm10
    total_pollution.append(total)

# ---------------- Graph ----------------
plt.figure(figsize=(8, 4))
plt.plot(years, total_pollution, marker="o", linewidth=3, markersize=10, color="#d35400")

plt.fill_between(years, total_pollution, color="#f5b041", alpha=0.3)

plt.title("Total Air Pollution in India Across Years (SO₂ + NO₂ + PM10)", fontsize=14, weight='bold')
plt.xlabel("Year", fontsize=12)
plt.ylabel("Total Pollution Value", fontsize=12)
plt.grid(True, linestyle="--", alpha=0.5)

for i, val in enumerate(total_pollution):
    plt.text(years[i], val + 5, str(val), ha='center', fontsize=10)

plt.tight_layout()
plt.show()